/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.util.Objects;
import javax.swing.JList;

/**
 *
 * @author Acer
 */
public class НовыйJPanel extends javax.swing.JPanel {

    /**
     * Creates new form НовыйJPanel
     */
    public НовыйJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "КрАЗ 250", "КрАЗ 256", "КрАЗ 255", "КрАЗ 257", "ГАЗ 2705", "ГАЗ 53", "ГАЗ 66", "ЗIЛ ММЗ 4502", "МАЗ 509", "МАЗ 5551", "МАЗ 5334", "УАЗ 469", "УАЗ 452", "ЗІЛ 130", "ЗІЛ 131", "ПАЗ 672","УАЗ 3741", "ЛАЗ 5252 8а", "Lanos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jFormattedTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFormattedTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField1MouseClicked(evt);
            }
        });

        jFormattedTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField2MouseClicked(evt);
            }
        });

        jLabel1.setText("Растояние(км)");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N

        jLabel3.setText("Использовано топлива");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));

        jButton1.setText("посчитать");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("посчитать");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("5%");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("10%");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("15%");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("отнять ");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("-----------------------");

        jLabel8.setText("jLabel8");

        jLabel9.setText("=");

        jLabel10.setText("количество ходок:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));

        jLabel12.setText("0%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jRadioButton1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jRadioButton2)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jRadioButton3)
                                                        .addGap(67, 67, 67)
                                                        .addComponent(jCheckBox1))
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(81, 81, 81)
                                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)))
                                .addGap(197, 197, 197))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(170, 170, 170)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(194, 194, 194)
                                        .addComponent(jLabel8)))
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jCheckBox1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField1MouseClicked
        if (jFormattedTextField2.getText() != null) {
            jFormattedTextField2.setText("");
        }
    }//GEN-LAST:event_jFormattedTextField1MouseClicked

    private void jFormattedTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField2MouseClicked
        if (jFormattedTextField1.getText() != null) {
            jFormattedTextField1.setText("");
        }
    }//GEN-LAST:event_jFormattedTextField2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel2.setText("");
        jLabel11.setText("");

        Value v = new Value();
        
        try {
            jLabel4.setText("");
            if (Double.valueOf(jFormattedTextField2.getText()) == 0) {
                jLabel4.setText("растояние не может быть 0");
            } else if (Double.valueOf(jFormattedTextField2.getText()) < 0) {
                jLabel4.setText("расстояние не может быть меньше 1км");
            } else if (jFormattedTextField2.getText() != "" || jFormattedTextField2.getText() != null) {

                //jCheckBox1.isSelected());
                jLabel2.setText(String.valueOf(v.kmOtvet(jList1.getModel().getElementAt(jList1.getSelectedIndex()),
                        Logic.avtoZap(),
                        Double.valueOf(jFormattedTextField2.getText()),
                        Double.valueOf(jFormattedTextField3.getText()),
                        jRadioButton1.isSelected(),
                        jRadioButton2.isSelected(),
                        jRadioButton3.isSelected(),
                        jCheckBox1.isSelected()) + " " + "км."));

            }
        } catch (IndexOutOfBoundsException boundsException) {
            jLabel4.setText("не выбран автомобиль");
        } catch (NumberFormatException exception) {
            jLabel11.setText("введите колличество ходок");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel2.setText("");
        jLabel11.setText("");

        double a = 0;
        Value v = new Value();

        try {
            jLabel4.setText("");
            if (Double.valueOf(jFormattedTextField1.getText()) == a) {
                jLabel4.setText("растояние не может быть 0");
            } else if (Double.valueOf(jFormattedTextField1.getText()) < 0) {
                jLabel4.setText("расстояние не может быть меньше 1км");
            } else if ((jList1.getSelectedIndex() == 3 || jList1.getSelectedIndex() == 1) && (jFormattedTextField3.getText() == "" || jFormattedTextField3 == null)) {
                jLabel11.setText("введите количество ходок");
            } else if (jFormattedTextField1.getText() != "" || jFormattedTextField1.getText() != null) {

                // jCheckBox1.isSelected());
                System.out.println(v.litrOtvet(jList1.getModel().getElementAt(jList1.getSelectedIndex()), Logic.avtoZap(), Double.valueOf(jFormattedTextField1.getText()), Double.valueOf(jFormattedTextField3.getText()), jRadioButton1.isSelected(),
                        jRadioButton2.isSelected(),
                        jRadioButton3.isSelected(),
                        jCheckBox1.isSelected()) + " " + "л.");
                jLabel2.setText(v.litrOtvet(jList1.getModel().getElementAt(jList1.getSelectedIndex()),
                        Logic.avtoZap(),
                        Double.valueOf(jFormattedTextField1.getText()),
                        Double.valueOf(jFormattedTextField3.getText()),
                        jRadioButton1.isSelected(),
                        jRadioButton2.isSelected(),
                        jRadioButton3.isSelected(),
                        jCheckBox1.isSelected()) + " " + "л.");

            }
        } catch (IndexOutOfBoundsException boundsException) {
            jLabel4.setText("не выбран автомобиль");
        } catch (NumberFormatException exception) {
            jLabel11.setText("введите колличество ходок");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        Value v = new Value();
        jLabel4.setText("");
        jLabel12.setText(String.valueOf(v.procentPro(jRadioButton1.isSelected(),
                jRadioButton2.isSelected(),
                jRadioButton3.isSelected(),
                jCheckBox1.isSelected()) * 100) + "%");
        try{
        jLabel13.setText("добавка " + String.valueOf(v.dobavka(jList1.getModel().getElementAt(jList1.getSelectedIndex()),
                Logic.avtoZap(),
                jRadioButton1.isSelected(),
                jRadioButton2.isSelected(),
                jRadioButton3.isSelected(),
                jCheckBox1.isSelected())) + "л.");
        } catch(ArrayIndexOutOfBoundsException aioobe){
        jLabel4.setText("не выбран автомобиль");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        Value v = new Value();
        jLabel4.setText("");
        jLabel12.setText(String.valueOf(v.procentPro(jRadioButton1.isSelected(),
                jRadioButton2.isSelected(),
                jRadioButton3.isSelected(),
                jCheckBox1.isSelected()) * 100) + "%");
        try{
        jLabel13.setText("добавка " + String.valueOf(v.dobavka(jList1.getModel().getElementAt(jList1.getSelectedIndex()),
                Logic.avtoZap(),
                jRadioButton1.isSelected(),
                jRadioButton2.isSelected(),
                jRadioButton3.isSelected(),
                jCheckBox1.isSelected())) + "л.");
        } catch(ArrayIndexOutOfBoundsException aioobe){
        jLabel4.setText("не выбран автомобиль");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        Value v = new Value();
        jLabel4.setText("");
        jLabel12.setText(String.valueOf(v.procentPro(jRadioButton1.isSelected(),
                jRadioButton2.isSelected(),
                jRadioButton3.isSelected(),
                jCheckBox1.isSelected()) * 100) + "%");
        try{
        jLabel13.setText("добавка " + String.valueOf(v.dobavka(jList1.getModel().getElementAt(jList1.getSelectedIndex()),
                Logic.avtoZap(),
                jRadioButton1.isSelected(),
                jRadioButton2.isSelected(),
                jRadioButton3.isSelected(),
                jCheckBox1.isSelected())) + "л.");
        } catch(ArrayIndexOutOfBoundsException aioobe){
        jLabel4.setText("не выбран автомобиль");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        Value v = new Value();
        jLabel4.setText("");
        jLabel12.setText(String.valueOf(v.procentPro(jRadioButton1.isSelected(),
                jRadioButton2.isSelected(),
                jRadioButton3.isSelected(),
                jCheckBox1.isSelected()) * 100) + "%");
        try{
        jLabel13.setText("добавка " + String.valueOf(v.dobavka(jList1.getModel().getElementAt(jList1.getSelectedIndex()),
                Logic.avtoZap(),
                jRadioButton1.isSelected(),
                jRadioButton2.isSelected(),
                jRadioButton3.isSelected(),
                jCheckBox1.isSelected())) + "л.");
        } catch(ArrayIndexOutOfBoundsException aioobe){
        jLabel4.setText("не выбран автомобиль");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jList1ValueChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        Value v = new Value();
        jLabel4.setText("");
        jLabel12.setText(String.valueOf(v.procentPro(jRadioButton1.isSelected(),
                jRadioButton2.isSelected(),
                jRadioButton3.isSelected(),
                jCheckBox1.isSelected()) * 100) + "%");
        try{
        jLabel13.setText("добавка " + String.valueOf(v.dobavka(jList1.getModel().getElementAt(jList1.getSelectedIndex()),
                Logic.avtoZap(),
                jRadioButton1.isSelected(),
                jRadioButton2.isSelected(),
                jRadioButton3.isSelected(),
                jCheckBox1.isSelected())) + "л.");
        } catch(ArrayIndexOutOfBoundsException aioobe){
        jLabel4.setText("не выбран автомобиль");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JList<String> jList1;
    public static javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
